import 'package:get/get.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': 'Hello',
      'name': 'Full Name',
      'email': 'Email',
      'submit': 'Submit',
      'next': 'Next',
      'janta_sewa': 'Janta Sewa',
      'registration': 'Registration',
      'provide_info': 'Provide Your Information',
      'general': 'General',
      'janpratinidhi': 'Janpratinidhi',
      'sangthan': 'Sangthan',
      'mediator': 'Mediator',
      'samajik_sanstha': 'Samajik Sanstha',
      'authorised_person': 'Authorised Person',
      'personal_details': 'Personal Details',
      'full_name': 'Full Name',
      'mobile_number': 'Mobile Number',
      'whatsapp_number': 'WhatsApp Number',
      'email_id': 'Email ID',
      'date_of_birth': 'Date of Birth',
      'dob_hint': 'dd/mm/yy',
      'blood_group': 'Blood Group',
      'aadhar_number': 'Aadhar Number',
      'location_details': 'Location Details',
      'address': 'Address',
      'state': 'State',
      'district': 'District',
      'block': 'Block',
      'vidhansabha': 'Vidhansabha',
      'city_village': 'City/ Village',
      'ward_number': 'Ward Number',
      'pincode': 'Pincode',
      'information': 'Information',
      'after_register_info':
          'After you register, you will get your login details and your user ID will be sent to your registered WhatsApp number.',
      'submit_btn': 'Submit',
      'login_here': 'Login Here',
      'email_phone': 'Email ID/Phone No',
      'enter_email_phone': 'Enter Email ID / Phone',
      'password': 'Password',
      'enter_password': 'Enter Password',
      'forgot_password': 'Forgot Your Password?',
      'login_btn': 'Login',
      'logout': 'Logout',
      'dont_have_account': 'Don\'t have an Account?',
      'register_here': 'Register Here',
      'select_app_language': 'Select App Language',
      'language': 'Language',

      'select_your_language': 'Select Your Language',
      'english': 'English',
      'hindi': 'Hindi',
      'enter_address': 'Enter Address',
      'enter_state': 'Enter State',
      'enter_district': 'Enter District',
      'enter_block': 'Enter Block',
      'enter_vidhansabha': 'Enter Vidhansabha',
      'enter_city_village': 'Enter City/ Village',
      'enter_ward_number': 'Enter Ward Number',
      'enter_pincode': 'Enter Pincode',
      'enter_full_name': 'Enter Full Name',
      'enter_mobile_number': 'Enter Mobile Number',
      'enter_whatsapp_number': 'Enter WhatsApp Number',
      'enter_email_id': 'Enter Email ID',
      'enter_blood_group': 'Enter Blood Group',
      'enter_aadhar_number': 'Enter Aadhar Number',
      'services_departments': 'Services & Departments',
      'rail_ticket_confirmation': 'Rail Ticket Confirmation',
      'parliament_visit': 'Parliament \n Visit',
      'parliament_visit_menu': 'Parliament Visit',
      'construction_work': 'Construction \n Work',
      'hospital_admission': 'Hospital \n Admission',
      'letter_request': 'Letter & Request',
      'recommendation_letter': 'Recommendation \n Letter',
      'recommendation_letter-m': 'Recommendation \n Letter',
      'complaint_letter': 'Complaint Letter',
      'complain_gov_emp': 'Complaint against Government Employee',
      'complain_of_politician': 'Complaint of Politician',
      'complain_of_national': 'Complaint of National Issue',
      'complain_of_mp_office': 'Complaint of MP Office',
      'suggestion_letter': 'Suggestion \n Letter',
      'budget_demand': 'Budget \n Demand',
      'contact_invitation': 'Contact & Invitation',
      'contact': 'Contact',
      'invitation': 'Invitation',
      'send_otp': 'Send OTP',
      'forgot_message':
      'Enter your Registered Mobile Number or Email Address. We’ll Send you a verification Code to Reset Your Password',
      'political': 'Political',
      'religious': 'Religious',
      'social': 'Social',
      'cultural': 'Cultural',
      'youth': 'Youth',
      'women': 'Women',
      'sangthan_registration': 'Organization Registration',
      'oragnization_name': 'Organization Name',
      'enter_oragnization_name': 'Enter Organization Name',
      'types_of_oragnization': 'Types of Organization',
      'date_of_establish': 'Date of Establishment',
      'enter_date_of_establish': 'Enter Date of Establishment',
      'contact_number': 'Contact Number',
      'enter_contact_number': 'Enter Contact Number',
      'auth_person_registration': 'Authorized Person Registration',
      'authorised_areas': 'Authorised Areas',
      'select_area_wise_rigths': 'Select Area Wise Rights',
      'enter_types_of_rights': 'Enter Type of Rights',
      'type_of_rights': 'Type of Rights',
      'members': 'Members',
      'org_appointed_officials': 'Org Appointed Officials',
      'types_of_auth': 'Types of Authorization',
      'ward': 'Ward',
      'gram_panchayat': 'Gram Panchayat',
      'blocks': 'Blocks',
      'assemblies': 'Assemblies',
      'janpad_panchayat_member': 'Janpad Panchayat Member',
      'zila_panchayat_member': 'Zila Panchayat Member',
      'nagar_panchayat_': 'Nagar Panchayat',
      'municipal_corporation_level': 'Municipal Corporation Level',
      'assembly': 'Assembly',
      'mandal': 'Mandal',
      'shakti_kendra': 'Shakti Kendra',
      'school': 'School',
      'college': 'College',
      'institute': 'Institute',
      'admission': 'Admission',
      'national': 'National',
      'welcome': 'Welcome',
      'job_recommendation_type': 'Job Recommendation Type',
      'posting': 'Posting',
      'types_of_posting': 'Types of Posting',
      'revised': 'Revised',
      'samajik_sanstha_registration': 'Social Organization Registration',
      'ticket_confirmation': 'Ticket Confirmation',
      'passenger_name': 'Passenger Name',
      'enter_passenger_name': 'Enter Passenger Name',
      'journey_date': 'Journey Date',
      'enter_journey_date': 'Enter Journey Date',
      'from': 'From',
      'to': 'To',
      'host_detail': 'Host Details',
      'pnr_number': 'PNR Number',
      'enter_pnr_number': 'Enter PNR Number',
      'train_number': 'Train Number',
      'enter_train_number': 'Enter Train Number',
      'train_name': 'Train Name',
      'enter_train_name': 'Enter Train Name',
      'birth_type': 'Berth Type',
      'enter_birth_type': 'Enter Berth Type',
      'age': 'Age',
      'enter_age': 'Enter Age',
      'gender': 'Gender',
      'enter_gender': 'Enter Gender',
      'select_your_category': 'Select Your Category',
      'headed_person_name': 'Headed Person Name',
      'headed_person_mobile_number': 'Headed Person Mobile Number',
      'constituency': 'Constituency',
      'date_of_visit': 'Date of Visit',
      'time_of_visit': 'Time of Visit',
      'total_number_of_members': 'Total Number of Members',
      'parliament_name': 'Parliament Name',
      'parliament_mobile_number': 'Parliament Mobile Number',
      'construction_work_menu': 'Construction Work',
      'new_work_demand': 'New Work Demand',
      'pending_work_completion': 'Pending Work Completion',
      'pending_work_completion-demand': 'Pending Work Completion',
      'actual_amount': 'Actual Amount',
      'beneficiary_oriented': 'Beneficiary Oriented',
      'department_name': 'Department Name',
      'animal': 'Animal',
      'recommendation_need': 'Recommendation Need',
      'husbandry': 'Husbandry',
      'panchayat': 'Panchayat',
      'agriculture': 'Agriculture',
      'horticulture': 'Horticulture',
      'fisheried': 'Fisheries',
      'labour': 'Labour',
      'social_welfare': 'Social Welfare',
      'other': 'Other',
      'amount': 'Amount',
      'work_name': 'Work Name',
      'work_detail': 'Work Detail',
      'tentative_amount': 'Tentative Amount',
      'remark': 'Remark',
      'demanded_person': 'Demanded Person',
      'demanded_person_mobile_number': 'Demanded Person Mobile Number',
      'village': 'Village',
      'upload_signed_documents': 'Upload Signed Documents',
      'patient_information': 'Patient Information',
      'patient_name': 'Patient Name',
      'enter_patient_name': 'Enter Patient Name',
      'name_of_attendent': 'Name of Attendant',
      'relation_with_patient': 'Relation with Patient',
      'father': 'Father',
      'mother': 'Mother',
      'brother': 'Brother',
      'wife': 'Wife',
      'share_this_app': 'Share this app',
      'rate_this_app': 'Rate this app',
      'privacy_policy': 'Privacy Policy',
      'terms_of_use': 'Terms of Use',
      'disease': 'Disease',
      'admission_type': 'Admission Type',
      'government_hospital': 'Government Hospital',
      'private_hospital': 'Private Hospital',
      'hospital_name': 'Hospital Name',
      'hospital_address': 'Hospital Address',
      'reference/sourc_of_request': 'Reference/Source of Request',
      'name_of_reference': 'Name of Reference',
      'post/designation_of_reference': 'Post/Designation of Reference',
      'mobile_number_of_reference': 'Mobile Number of Reference',
      'hospital_contact_person(s)': 'Hospital Contact Person(s)',
      'desigantion': 'Designation',
      'suggestion_letter_menu': 'Suggestion Letter Menu',
      'suggestion_for_people': 'Suggestion for People',
      'suggestion_for_government_schemes': 'Suggestion for Government Schemes',
      'suggestion_for_government_department':
      'Suggestion for Government Department',
      'suggestion_for_mp_office': 'Suggestion for MP Office',
      'suggestion_type': 'Suggestion Type',
      'suggestion_for': 'Suggestion For',
      'other_suggestion': 'Other Suggestion',
      'complain_letter_m': 'Complaint Letter',
      'compain_of_gov_employee': 'Complaint of Government Employee',
      'applicant_name': 'Applicant Name',
      'complain_type': 'Complaint Type',
      'complain_department_name': 'Complaint Department Name',
      'employee_name': 'Employee Name',
      'designation': 'Designation',
      'brief_detail_of_complain': 'Brief Detail of Complaint',
      'politician_name': 'Politician Name',
      'budget_demand_me': 'Budget Demand',
      'requested for': 'Requested For',
      'new government office': 'New Government Office',
      'new government major work': 'New Government Major Work',
      'Name of the Office Work Demanded': 'Name of the Office Work Demanded',
      'office work demanded': 'Office Work Demanded',
      'name of the major Work Demanded': 'Name of the Major Work Demanded',
      'major work demanded': 'Major Work Demanded',
      'level_of_government': 'Level of Government',
      'National Government': 'National Government',
      'State Government': 'State Government',
      'compain_of_national/state_work': 'Complaint of National/State Work',
      'arrangement': 'Arrangement',
      'Staff': 'Staff',
      'journey_quotes': 'Leadership is not about power, it’s about purpose — serving every citizen with commitment and care."',
      'beneficiary_oriendted': 'Beneficiary Oriented',
      'compain_of_mp_office': 'Complaint of MP Office',
      'local_program': 'Local Program',
      'meeting': 'Meeting',
      'invitation form': 'Invitation Form',
      'types_of_invitation': 'Types of Invitation',
      'invitation_for_meeting': 'Invitation for Meeting',
      'invitation_for_event': 'Invitation for Event',
      'meeting_agenda': 'Meeting Agenda',
      'organization_name': 'Organization Name',
      'program_name': 'Program Name',
      'village/word': 'Village/Ward',
      'date': 'Date',
      'time': 'Time',
      'status': 'Status',
      'contact_page': 'Contact Page',
      'location': 'Location',
      'remarks': 'Remarks',
      'contact_person_name': 'Contact Person Name',
      'contact_person_mobile_number': 'Contact Person Mobile Number',
      'brief_detail_of_suggestion': 'Brief Detail of Suggestion',
      'suggestion_for_Gov_scheme': 'Suggestion for Government Scheme',
      'transfer': 'Transfer',
      'view_details': 'View Details',
      'types_of_transfer': 'Types of Transfer',
      'mobile': 'Mobile',
      'my_account': 'My Account',
      'posted_office': 'Posted Office',
      'opted_office': 'Opted Office',
      'reason_for_transfer': 'Reason for Transfer',
      'department': 'Department',
      'reason_of_problem': 'Reason of Problem',
      'types_of_admission': 'Types of Admission',
      'student_name': 'Student Name',
      'class/Course_name': 'Class/Course Name',
      'award': 'Award',
      'opted_land_address': 'Opted Land Address',
      'reason_for_land_allotment': 'Reason for Land Allotment',
      'types_of_award': 'Types of Award',
      'career_achievement': 'Career Achievement',
      'award_name': 'Award Name',
      'brief_details': 'Brief Details',
      'home' : 'Home',
      'quarter_allotment': 'Quarter Allotment',
      'types_of_allotment': 'Types of Allotment',
      'opted_quarter_department': 'Opted Quarter Department',
      'from_whom_to_opted': 'From Whom to Opted',
      'opted_quarter_address': 'Opted Quarter Address',
      'reason_for_quarter_allotment': 'Reason for Quarter Allotment',
      'land_allotment': 'Land Allotment',
      'job_recommendation': 'Job Recommendation',
      'financial_recommendation': 'Financial Recommendation',
      'cultural_programme': 'Cultural Programme',
      'cultural_programme_name': 'Cultural Programme Name',
      'cultural_programme_owner_name': 'Cultural Programme Owner Name',
      'in_behalf_of': 'In Behalf Of',
      'other_recommendation': 'Other Recommendation',
      'new': 'New',
      'existing': 'Existing',
      'bsp': 'BSP',
      "speech": "Speech",
      "view_more": "View More",
      "photo_gallery": "Photo Gallery",
      "join_bjp": "Join BJP",
      "join_volunteer": "Join as Volunteer",
       'upcoming_event': 'Upcoming Event',
      'our_journey': 'Our Journey',
      'notifications': 'Notifications',
      'contact_us': 'Contact Us',
      'settings': 'Settings',
      'state govt': 'State Govt',
      'central govt': 'Central Govt',
      'private': 'Private',
      'back_to_login': 'Back To Login',
      'verification_message':
          'Please enter the OTP (One Time Password) Sent to your registered email/phone number to complete your verification',
      'otp_verification': 'OTP Verification',
      'Didn’t_get_the_code?': 'Didn’t get the code?',
      'resend_otp': 'Resend OTP',
      'remaining_time': 'Remaining Time',
      'create_a_new_password': 'Create a New Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'cancel': 'Cancel',
      'save': 'Save',
      'verify_otp': 'Verify OTP',
    },
    'hi_IN': {
      'hello': 'नमस्ते',
      'name': 'पूरा नाम',
      'email': 'ईमेल',
      'submit': 'जमा करें',
      'next': 'आगे बढ़े',
      'janta_sewa': 'जनता सेवा',
      'registration': 'पंजीकरण',
      'provide_info': 'अपनी जानकारी प्रदान करें',
      'general': 'सामान्य',
      'janpratinidhi': 'जनप्रतिनिधि',
      'sangthan': 'संगठन',
      'mediator': 'मध्यस्थ',
      'samajik_sanstha': 'सामाजिक संस्था',
      'authorised_person': 'अधिकृत व्यक्ति',
      'personal_details': 'व्यक्तिगत विवरण',
      'full_name': 'पूरा नाम',
      'mobile_number': 'मोबाइल नंबर',
      'whatsapp_number': 'व्हाट्सएप नंबर',
      'email_id': 'ईमेल आईडी',
      'date_of_birth': 'जन्म तिथि',
      'dob_hint': 'दिन/माह/वर्ष',
      'blood_group': 'ब्लड ग्रुप',
      'aadhar_number': 'आधार नंबर',
      'location_details': 'स्थान विवरण',
      'address': 'पता',
      'state': 'राज्य',
      'district': 'जिला',
      'block': 'ब्लॉक',
      'vidhansabha': 'विधानसभा',
      'city_village': 'शहर/गांव',
      'ward_number': 'वार्ड नंबर',
      'pincode': 'पिनकोड',
      'information': 'जानकारी',
      'after_register_info':
          'पंजीकरण के बाद, आपको अपने लॉगिन विवरण मिलेंगे और आपकी यूजर आईडी आपके पंजीकृत व्हाट्सएप नंबर पर भेज दी जाएगी।',
      'submit_btn': 'जमा करें',
      'login_here': 'यहाँ लॉगिन करें',
      'email_phone': 'ईमेल आईडी/फोन नंबर',
      'enter_email_phone': 'ईमेल आईडी / फोन दर्ज करें',
      'password': 'पासवर्ड',
      'enter_password': 'पासवर्ड दर्ज करें',
      'forgot_password': 'क्या आप पासवर्ड भूल गए?',
      'login_btn': 'लॉगिन',
      'dont_have_account': 'खाता नहीं है?',
      'register_here': 'यहाँ रजिस्टर करें',
      'select_app_language': 'ऐप भाषा चुनें',
      'select_your_language': 'अपनी भाषा का चयन करें',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'enter_address': 'पता दर्ज करें',
      'enter_state': 'राज्य दर्ज करें',
      'enter_district': 'जिला दर्ज करें',
      'enter_block': 'ब्लॉक दर्ज करें',
      'enter_vidhansabha': 'विधानसभा दर्ज करें',
      'enter_city_village': 'शहर/गांव दर्ज करें',
      'enter_ward_number': 'वार्ड नंबर दर्ज करें',
      'enter_pincode': 'पिनकोड दर्ज करें',
      'enter_full_name': 'पूरा नाम दर्ज करें',
      'enter_mobile_number': 'मोबाइल नंबर दर्ज करें',
      'enter_whatsapp_number': 'व्हाट्सएप नंबर दर्ज करें',
      'enter_email_id': 'ईमेल आईडी दर्ज करें',
      'enter_blood_group': 'ब्लड ग्रुप दर्ज करें',
      'enter_aadhar_number': 'आधार नंबर दर्ज करें',
      'services_departments': 'सेवाएँ और विभाग',
      'rail_ticket_confirmation': 'रेल टिकट पुष्टि',
      'parliament_visit': 'संसद यात्रा',
      'parliament_visit_menu': 'संसद यात्रा',
      'beneficiary_oriendted': 'लाभार्थी उन्मुख',
      'recommendation_need': 'सिफारिश की आवश्यकता',
      'construction_work': 'निर्माण कार्य',
      'hospital_admission': 'अस्पताल में भर्ती',
      'letter_request': 'पत्र और अनुरोध',
      'recommendation_letter-m': 'सिफारिश पत्र',
      'complaint_letter': 'शिकायत पत्र',
      'complain_gov_emp': 'सरकारी कर्मचारी के खिलाफ शिकायत',
      'complain_of_politician': 'राजनीतिज्ञ की शिकायत',
      'complain_of_national': 'राष्ट्रीय मुद्दे की शिकायत',
      'complain_of_mp_office': 'सांसद कार्यालय की शिकायत',
      'suggestion_letter': 'सुझाव पत्र',
      'budget_demand': 'बजट मांग',
      'contact_invitation': 'संपर्क और निमंत्रण',
      'contact': 'संपर्क',
      'invitation': 'निमंत्रण',
      'send_otp': 'ओटीपी भेजें',
      'forgot_message':
          'अपना पंजीकृत मोबाइल नंबर या ईमेल पता दर्ज करें। हम आपको पासवर्ड रीसेट करने के लिए एक सत्यापन कोड भेजेंगे',
      'political': 'राजनीतिक',
      'religious': 'धार्मिक',
      'social': 'सामाजिक',
      'cultural': 'सांस्कृतिक',
      'youth': 'युवा',
      'women': 'महिला',
      'status': 'स्थिति',
      'sangthan_registration': 'संगठन पंजीकरण',
      'oragnization_name': 'संगठन का नाम',
      'enter_oragnization_name': 'संगठन का नाम दर्ज करें',
      'types_of_oragnization': 'संगठन के प्रकार',
      'date_of_establish': 'स्थापना तिथि',
      'enter_date_of_establish': 'स्थापना तिथि दर्ज करें',
      'contact_number': 'संपर्क नंबर',
      'enter_contact_number': 'संपर्क नंबर दर्ज करें',
      'auth_person_registration': 'अधिकृत व्यक्ति पंजीकरण',
      'authorised_areas': 'अधिकृत क्षेत्र',
      'select_area_wise_rigths': 'क्षेत्रवार अधिकार चुनें',
      'enter_types_of_rights': 'अधिकार का प्रकार दर्ज करें',
      'type_of_rights': 'अधिकार का प्रकार',
      'members': 'सदस्य',
      'reason_of_problem': 'समस्या का कारण',
      'org_appointed_officials': 'संगठन द्वारा नियुक्त अधिकारी',
      'types_of_auth': 'अधिकार के प्रकार',
      'ward': 'वार्ड',
      'gram_panchayat': 'ग्राम पंचायत',
      'blocks': 'ब्लॉक',
      'assemblies': 'विधानसभाएँ',
      'janpad_panchayat_member': 'जनपद पंचायत सदस्य',
      'zila_panchayat_member': 'जिला पंचायत सदस्य',
      'nagar_panchayat_': 'नगर पंचायत',
      'municipal_corporation_level': 'नगर निगम स्तर',
      'assembly': 'विधानसभा',
      'mandal': 'मंडल',
      'shakti_kendra': 'शक्ति केंद्र',
      'school': 'स्कूल',
      'college': 'कॉलेज',
      'institute': 'संस्थान',
      'admission': 'प्रवेश',
      'national': 'राष्ट्रीय',
      'welcome': 'स्वागत है',
      'view_details': 'विवरण देखें',
      'posting': 'पदस्थापन',
      'types_of_posting': 'पदस्थापन के प्रकार',
      'revised': 'संशोधित',
      'samajik_sanstha_registration': 'सामाजिक संस्था पंजीकरण',
      'ticket_confirmation': 'टिकट पुष्टि',
      'passenger_name': 'यात्री का नाम',
      'enter_passenger_name': 'यात्री का नाम दर्ज करें',
      'journey_date': 'यात्रा तिथि',
      'enter_journey_date': 'यात्रा तिथि दर्ज करें',
      'from': 'कहाँ से',
      'to': 'कहाँ तक',
      'pnr_number': 'पीएनआर नंबर',
      'enter_pnr_number': 'पीएनआर नंबर दर्ज करें',
      'train_number': 'ट्रेन नंबर',
      'enter_train_number': 'ट्रेन नंबर दर्ज करें',
      'train_name': 'ट्रेन का नाम',
      'enter_train_name': 'ट्रेन का नाम दर्ज करें',
      'birth_type': 'बर्थ प्रकार',
      'enter_birth_type': 'बर्थ प्रकार दर्ज करें',
      'age': 'आयु',
      'enter_age': 'आयु दर्ज करें',
      'gender': 'लिंग',
      'enter_gender': 'लिंग दर्ज करें',
      'select_your_category': 'अपनी श्रेणी चुनें',
      'headed_person_name': 'प्रमुख व्यक्ति का नाम',
      'headed_person_mobile_number': 'प्रमुख व्यक्ति का मोबाइल नंबर',
      'constituency': 'निर्वाचन क्षेत्र',
      'date_of_visit': 'भ्रमण की तिथि',
      'time_of_visit': 'भ्रमण का समय',
      'total_number_of_members': 'सदस्यों की कुल संख्या',
      'parliament_name': 'संसद का नाम',
      'parliament_mobile_number': 'संसद का मोबाइल नंबर',
      'construction_work_menu': 'निर्माण कार्य',
      'new_work_demand': 'नया कार्य मांग',
      'pending_work_completion': 'लंबित कार्य पूर्णता',
      'pending_work_completion-demand': 'लंबित कार्य पूर्णता',
      'actual_amount': 'वास्तविक राशि',
      'beneficiary_oriented': 'लाभार्थी उन्मुख',
      'department_name': 'विभाग का नाम',
      'animal': 'पशु',
      'journey_quotes': 'नेतृत्व का मतलब शक्ति नहीं है, बल्कि इसका मतलब है उद्देश्य - प्रतिबद्धता और देखभाल के साथ प्रत्येक नागरिक की सेवा करना।"',
      'husbandry': 'पशुपालन',
      'panchayat': 'पंचायत',
      'agriculture': 'कृषि',
      'horticulture': 'बागवानी',
      'fisheried': 'मत्स्य पालन',
      'labour': 'श्रम',
      'social_welfare': 'सामाजिक कल्याण',
      'other': 'अन्य',
      'amount': 'राशि',
      'work_name': 'कार्य का नाम',
      'work_detail': 'कार्य का विवरण',
      'tentative_amount': 'अनुमानित राशि',
      'remark': 'टिप्पणी',
      'my_account': 'मेरा खाता',
      'demanded_person': 'मांगकर्ता',
      'demanded_person_mobile_number': 'मांगकर्ता का मोबाइल नंबर',
      'village': 'गांव',
      'upload_signed_documents': 'हस्ताक्षरित दस्तावेज़ अपलोड करें',
      'patient_information': 'रोगी की जानकारी',
      'patient_name': 'रोगी का नाम',
      'enter_patient_name': 'रोगी का नाम दर्ज करें',
      'name_of_attendent': 'सहायक का नाम',
      'relation_with_patient': 'रोगी से संबंध',
      'father': 'पिता',
      'mother': 'माता',
      'brother': 'भाई',
      'wife': 'पत्नी',
      'disease': 'रोग',
      'admission_type': 'प्रवेश प्रकार',
      'government_hospital': 'सरकारी अस्पताल',
      'private_hospital': 'निजी अस्पताल',
      'hospital_name': 'अस्पताल का नाम',
      'hospital_address': 'अस्पताल का पता',
      'reference/sourc_of_request': 'संदर्भ/अनुरोध का स्रोत',
      'name_of_reference': 'संदर्भ का नाम',
      'post/designation_of_reference': 'संदर्भ का पद/पदनाम',
      'mobile_number_of_reference': 'संदर्भ का मोबाइल नंबर',
      'hospital_contact_person(s)': 'अस्पताल संपर्क व्यक्ति',
      'desigantion': 'पदनाम',
      'contact_page': 'संपर्क पृष्ठ',
      'home': 'होम',
      'upcoming_event': 'आगामी कार्यक्रम',
      'our_journey': 'हमारी यात्रा',
      'notifications': 'सूचनाएं',
      'contact_us': 'संपर्क करें',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'suggestion_letter_menu': 'सुझाव पत्र मेनू',
      'suggestion_for_people': 'लोगों के लिए सुझाव',
      'suggestion_for_government_schemes': 'सरकारी योजनाओं के लिए सुझाव',
      'suggestion_for_government_department': 'सरकारी विभाग के लिए सुझाव',
      'suggestion_for_mp_office': 'सांसद कार्यालय के लिए सुझाव',
      'suggestion_type': 'सुझाव का प्रकार',
      'suggestion_for': 'के लिए सुझाव',
      'other_suggestion': 'अन्य सुझाव',
      'complain_letter_m': 'शिकायत पत्र',
      'compain_of_gov_employee': 'सरकारी कर्मचारी की शिकायत',
      'applicant_name': 'आवेदक का नाम',
      'complain_type': 'शिकायत का प्रकार',
      'complain_department_name': 'शिकायत विभाग का नाम',
      'employee_name': 'कर्मचारी का नाम',
      'designation': 'पद',
      'brief_detail_of_complain': 'शिकायत का संक्षिप्त विवरण',
      'politician_name': 'राजनीतिज्ञ का नाम',
      'budget_demand_me': 'बजट मांग',
      'requested for': 'मांग की गई',
      'new government office': 'नया सरकारी कार्यालय',
      'new government major work': 'नया सरकारी प्रमुख कार्य',
      'Name of the Office Work Demanded': 'मांगे गए कार्यालय कार्य का नाम',
      'office work demanded': 'मांगा गया कार्यालय कार्य',
      'name of the major Work Demanded': 'मांगे गए प्रमुख कार्य का नाम',
      'major work demanded': 'मांगा गया प्रमुख कार्य',
      'level_of_government': 'सरकार का स्तर',
      'National Government': 'राष्ट्रीय सरकार',
      'State Government': 'राज्य सरकार',
      'compain_of_national/state_work': 'राष्ट्रीय/राज्य कार्य की शिकायत',
      'arrangement': 'व्यवस्था',
      'Staff': 'स्टाफ',
      'compain_of_mp_office': 'सांसद कार्यालय की शिकायत',
      'local_program': 'स्थानीय कार्यक्रम',
      'meeting': 'बैठक',
      'invitation form': 'निमंत्रण फॉर्म',
      'types_of_invitation': 'निमंत्रण के प्रकार',
      'invitation_for_meeting': 'बैठक के लिए निमंत्रण',
      'invitation_for_event': 'कार्यक्रम के लिए निमंत्रण',
      'meeting_agenda': 'बैठक का एजेंडा',
      'organization_name': 'संगठन का नाम',
      'program_name': 'कार्यक्रम का नाम',
      'village/word': 'गांव/वार्ड',
      'date': 'तारीख',
      'time': 'समय',
      'location': 'स्थान',
      'remarks': 'टिप्पणी',
      'contact_person_name': 'संपर्क व्यक्ति का नाम',
      'contact_person_mobile_number': 'संपर्क व्यक्ति का मोबाइल नंबर',
      'brief_detail_of_suggestion': 'सुझाव का संक्षिप्त विवरण',
      'suggestion_for_Gov_scheme': 'सरकारी योजना के लिए सुझाव',
      'transfer': 'स्थानांतरण',
      'types_of_transfer': 'स्थानांतरण के प्रकार',
      'mobile': 'मोबाइल',
      'posted_office': 'पोस्टेड कार्यालय',
      'opted_office': 'वांछित कार्यालय',
      'reason_for_transfer': 'स्थानांतरण का कारण',
      'department': 'विभाग',
      'cultural_programme_name': 'सांस्कृतिक कार्यक्रम का नाम',
      'cultural_programme_owner_name': 'सांस्कृतिक कार्यक्रम के मालिक का नाम',
      'in_behalf_of': 'की ओर से',
      'types_of_admission': 'प्रवेश के प्रकार',
      'student_name': 'छात्र का नाम',
      'class/Course_name': 'कक्षा/कोर्स का नाम',
      'award': 'पुरस्कार',
      'types_of_award': 'पुरस्कार के प्रकार',
      'career_achievement': 'करियर उपलब्धि',
      'award_name': 'पुरस्कार का नाम',
      'host_detail': 'होस्ट विवरण',
      'brief_details': 'संक्षिप्त विवरण',
      'quarter_allotment': 'क्वार्टर आवंटन',
      'types_of_allotment': 'आवंटन के प्रकार',
      'opted_quarter_department': 'चयनित क्वार्टर विभाग',
      'from_whom_to_opted': 'किससे चयनित',
      'opted_quarter_address': 'चयनित क्वार्टर का पता',
      'reason_for_quarter_allotment': 'क्वार्टर आवंटन का कारण',
      'land_allotment': 'भूमि आवंटन',
      'job_recommendation': 'नौकरी की सिफारिश',
      'job_recommendation_type': 'नौकरी की सिफारिश का प्रकार',
      'financial_recommendation': 'वित्तीय सिफारिश',
      'cultural_programme': 'सांस्कृतिक कार्यक्रम',
      'other_recommendation': 'अन्य सिफारिश',
      'new': 'नया',
      'existing': 'मौजूदा',
      'bsp': 'बीएसपी',
      'state govt': 'राज्य सरकार',
      'central govt': 'केंद्र सरकार',
      'private': 'निजी',
      'back_to_login': 'लॉगिन पर वापस जाएं',
      // ignore: equal_keys_in_map
      'logout': 'लॉग आउट',
       'language': 'भाषा',
      'share_this_app': 'ऐप शेयर करें',
      'rate_this_app': 'ऐप को रेट करें',
      'privacy_policy': 'गोपनीयता नीति',
      'terms_of_use': 'उपयोग की शर्तें',
      'verification_message':
          'कृपया अपना सत्यापन पूरा करने के लिए अपने पंजीकृत ईमेल/फोन नंबर पर भेजा गया ओटीपी (वन टाइम पासवर्ड) दर्ज करें',
      'otp_verification': 'ओटीपी सत्यापन',
      'Didn’t_get_the_code?': 'कोड नहीं मिला?',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'remaining_time': 'शेष समय',
      'create_a_new_password': 'नया पासवर्ड बनाएं',
      'new_password': 'नया पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'verify_otp': 'ओटीपी सत्यापित करें',
      "speech": "भाषण",
      "view_more": "और देखें",
      "photo_gallery": "फोटो गैलरी",
      "join_bjp": "भाजपा में शामिल हों",
      "join_volunteer": "स्वयंसेवक के रूप में जुड़ें"
    },
  };
}
